version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.2.1
    links:
      - zookeeper:zk
    ports:
      - 9092:9092
    environment:
      HOSTNAME_COMMAND: "getent hosts `hostname` | cut -d' ' -f1"
#      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
#      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://10.200.0.105:9092"
#      KAFKA_BROKER_ID: 1
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - $PWD/var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper